### ISSUE TITLE
Creating Login Page using Html, CSS, JS

### ISSUE THREAD

**Issue by shrek-28** [Rupa-Rd/Open-Source-Galaxy#12]
- [ ] 
![Screenshot 2024-06-17 095138](https://github.com/Rupa-Rd/Open-Source-Galaxy/assets/122817076/2e41687f-21f8-4c26-afef-0c67baf7b6d4)

This is the shape of the current file. 

Changes I suggest:
1. Addition of OAuth using Flask 
2. General Changes in UI Design, by removing black space, and adding suitable images etc. 
3. New authentication user database.

**Comment by Rupa-Rd** [comment]
@shrek-28 Can you create a new login page from scratch using MERN stack?
Tell me if you're comfortable

**Comment by shrek-28** [comment]
> Owner

I can use HTML, CSS and JS, but only can build OAuth using Flask.

**Comment by Rupa-Rd** [comment]
@shrek-28 For now, just create a front-end of the login page and link to the website.

**Comment by avyaanverma** [comment]
Can I work on the oauth as I am aware of the meen stack and have done it before. I'm comfortable

**Comment by Rupa-Rd** [comment]
This issue is getting closed since the assignee is not active and also the login is done using oauth by default. You can create issues regarding login page styling. I'll personally make edits on the login page api. 

Thank you!
