### ISSUE TITLE
Changing the Website Background color

### ISSUE THREAD

**Issue by Rupa-Rd** [Rupa-Rd/Open-Source-Galaxy#13]
## Current condition
![image](https://github.com/Rupa-Rd/Open-Source-Galaxy/assets/102663541/4807242f-fb14-4b02-8519-7a1d75d7a054)

## Expected behavior:

Change the background of the website for both light and dark mode according to the style of the website

**Comment by avyaanverma** [comment]
Let me work on this I will be soon posting a pr
