### ISSUE TITLE
Creating a new blog page

### ISSUE THREAD

**Issue by Rupa-Rd** [Rupa-Rd/Open-Source-Galaxy#15]
## Description

- Create a new blog page to display the experience of the open source events listed on the open source galaxy website.
- Use the same styling format as main page
- Use the same font, color

**Comment by Ayushswirlon** [comment]
hey i can help you to achieve the given task also raised an issue regarding the header and footer already. let me contribute to the project by assigning it to me

**Comment by Rupa-Rd** [comment]
Sure, @Ayushswirlon go for it!.

**Comment by Ayushswirlon** [comment]
https://github.com/Rupa-Rd/Open-Source-Galaxy/assets/136717301/b88d7778-0bab-420d-8ffc-dbbcc44a6d85

had done till that anything else you are expecting after this
