### ISSUE TITLE
Improve card UI

### ISSUE THREAD

**Issue by k0msenapati** [Rupa-Rd/Open-Source-Galaxy#17]
![image](https://github.com/Rupa-Rd/Open-Source-Galaxy/assets/92045934/60ff300c-342a-4bea-908b-6706a89dc317)

Here its hard to distinguish title, button and link
So these can be designed uniquely with icons and background color of cards can be changed and glassmorphism, roundedness can be introduced

**Comment by Rupa-Rd** [comment]
Can you provide some basic style on how it will look after development?

**Comment by k0msenapati** [comment]
![image](https://github.com/Rupa-Rd/Open-Source-Galaxy/assets/92045934/836daa2e-b135-44c0-ada3-4c79e01945ac)

**Comment by Rupa-Rd** [comment]
Yeah Go ahead and work on it.!
But can you choose better color for the outline of the projects?
