### ISSUE TITLE
Enhancement of Navbar with Closed and upcoming open source events

### ISSUE THREAD

**Issue by Mehak-Mattoo** [Rupa-Rd/Open-Source-Galaxy#18]
1.  informing users about the website (with changes in bg color)
2. the navbar with links to closed, upcoming projects, login and sign up

**Comment by Rupa-Rd** [comment]
Cool, You can work on the Navbar with closed, upcoming project links

**Comment by rajdesai17** [comment]
okay, i'll start the work once navbar is updated.
