### ISSUE TITLE
Adding a FAQ component in homepage detailing what is open source contribution and the needed knowledge to do so 

### ISSUE THREAD

**Issue by shrek-28** [Rupa-Rd/Open-Source-Galaxy#19]
Addition of an FAQ Page to the homepage detailing:
1. What is an open source contribution
2. Why are open source contributions important?
3. How to do an open source contribution.

**Comment by k0msenapati** [comment]
I would like to work on this

**Comment by Rupa-Rd** [comment]
@kom-senapati Go for it
