### ISSUE TITLE
Change of Card Structure 

### ISSUE THREAD

**Issue by shrek-28** [Rupa-Rd/Open-Source-Galaxy#20]
![Screenshot 2024-06-17 114256](https://github.com/Rupa-Rd/Open-Source-Galaxy/assets/122817076/c51e3771-e637-4dcd-ba15-d747d1d8333e)

Changing Card Structure to 
1. Making the image to the link of the homepage of the open source program
2. Changing "Email" to icon of mail.
3. Adding LinkedIn and other social media links of the organization. 
4. Adding a probable timeline

**Comment by avyaanverma** [comment]
I want to work on this issue
