### ISSUE TITLE
Changing the login button and Search Area

### ISSUE THREAD

**Issue by shatanshu3006** [Rupa-Rd/Open-Source-Galaxy#22]
1. Adding border radius
2. Adding Hover effect 
3. Adding a transition effect 
4. The button goes a little darker and floats on hovering 
5. Tooltips (hovering tip)
6. Similar hovering and Tooltips effect on Search Icon (with the same color changes [little darker])

Before:
<img width="155" alt="Screenshot 2024-06-17 at 12 00 15 PM" src="https://github.com/Rupa-Rd/Open-Source-Galaxy/assets/100084737/b5ab16cd-817d-4835-9f38-6d6890480226">

After:
<img width="166" alt="Screenshot 2024-06-17 at 12 11 43 PM" src="https://github.com/Rupa-Rd/Open-Source-Galaxy/assets/100084737/f9219d6f-9a7d-4cde-b6bc-50dff3e5d94d">

Tooltip update:
<img width="190" alt="Screenshot 2024-06-17 at 12 15 14 PM" src="https://github.com/Rupa-Rd/Open-Source-Galaxy/assets/100084737/240e8882-cc00-419e-8f5b-f2ba38c38f10">

**Comment by Rupa-Rd** [comment]
@shatanshu3006 Go ahead and work on this

**Comment by shatanshu3006** [comment]
Done!

**Comment by Rupa-Rd** [comment]
@shatanshu3006 Do not close the issue till the PR gets merged

**Comment by shatanshu3006** [comment]
> @shatanshu3006 Do not close the issue till the PR gets merged

Apologies! Actually it's my first time!
Won't happen again
