### ISSUE TITLE
Add New Open Source Programs to the List

### ISSUE THREAD

**Issue by Kaustav2410** [Rupa-Rd/Open-Source-Galaxy#23]
Description:

Summary:
To provide the users with more opportunities and resources, I propose adding the following open source programs to the existing list. These programs offer valuable learning experiences, mentorship, and community engagement for developers of all levels.

Programs to Add:

Hyperledger Mentorship Program
Description: Aimed at students and professionals to work on Hyperledger projects under the guidance of mentors.

Reinforcement Learning Open Source Fest by Microsoft
Description: An annual program focused on projects related to reinforcement learning and machine learning.

LFN Mentorship Program
Description: Offers students opportunities to work on Linux Foundation Networking projects.

Summer of Nix
Description: A summer program to work on projects related to the Nix ecosystem.

24 Pull Requests
Description: An annual initiative encouraging developers to make 24 pull requests to open source projects in December.

GitHub Octernship Program
Description: A program connecting students with industry partners for internships focused on open source projects.

FOSSASIA Internship Program
Description: An internship program offering students the chance to work on FOSSASIA projects.

Quansight Internship
Description: Offers internships to work on data science and open-source projects.

Including these programs will enrich our list, providing more diverse and valuable opportunities for the users. If there are any other suggestions or programs that should be included, please mention them in the comments.

**Comment by Rupa-Rd** [comment]
@Kaustav2410 Go ahead and work on this issue.
Kindly don't change any styling format of the website.
