### ISSUE TITLE
Adding contributor's image list under readme

### ISSUE THREAD

**Issue by Arpcoder** [Rupa-Rd/Open-Source-Galaxy#27]

**Comment by Rupa-Rd** [comment]
@Arpcoder  Provide a detailed description of your improvement or approach

**Comment by deepesh611** [comment]
I agree, adding profile pics of all the contributers in README.md.
Something like this
![image](https://github.com/Rupa-Rd/Open-Source-Galaxy/assets/123585104/6f0f511a-9c21-4909-94d8-0a004146ee59)

**Comment by deepesh611** [comment]
so what do u think @Rupa-Rd

**Comment by Rupa-Rd** [comment]
This is cool! @deepesh611 , but try to include only the images of the contributors. And by clicking their image it should take to their profile

**Comment by deepesh611** [comment]
> This is cool! @deepesh611 , but try to include only the images of the contributors. And by clicking their image it should take to their profile

But then, you will have to manually add the new contributors...

**Comment by Rupa-Rd** [comment]
> > This is cool! @deepesh611 , but try to include only the images of the contributors. And by clicking their image it should take to their profile
> 
> But then, you will have to manually add the new contributors...

Yeah, I'll tc of it. Add the current contributors including you!. 😊

**Comment by deepesh611** [comment]
> > > This is cool! @deepesh611 , but try to include only the images of the contributors. And by clicking their image it should take to their profile
> > 
> > 
> > But then, you will have to manually add the new contributors...
> 
> Yeah, I'll tc of it. Add the current contributors including you!. 😊

alright, I'll be including myself and the current contributors, and submit a separate PR in the updated readme 👍
