### ISSUE TITLE
Icon can be added

### ISSUE THREAD

**Issue by KavyaBS123** [Rupa-Rd/Open-Source-Galaxy#33]
Icon brings better UX and authentication to the website. It can be added with a good design
![Screenshot (454)](https://github.com/Rupa-Rd/Open-Source-Galaxy/assets/148982177/ceb6c20b-c7c8-46e5-a6fc-c35c13c7a2e5)

**Comment by KavyaBS123** [comment]
Hey @Rupa-Rd I am VSoC contributor if you assign me this issue I can give a prototype of a better logos

**Comment by Rupa-Rd** [comment]
@KavyaBS123 , You're currently mentioned the changes for old codebases and UI.
Try to pull the recent changes and raise a issue
