### ISSUE TITLE
Add an "About Us" section to the website

### ISSUE THREAD

**Issue by rajdesai17** [Rupa-Rd/Open-Source-Galaxy#38]
The website currently lacks a dedicated "About Us" section. About us section can provide valuable information and build trust with potential users

**Comment by Rupa-Rd** [comment]
@rajdesai17  You can start working on this issue when the navbar design is finished. i.e, issue #18

**Comment by rajdesai17** [comment]
Hello, I submitted the PR. Do check. https://github.com/Rupa-Rd/Open-Source-Galaxy/pull/50#issue-2372259196
