### ISSUE TITLE
Styling Font and Color

### ISSUE THREAD

**Issue by k0msenapati** [Rupa-Rd/Open-Source-Galaxy#4]
![image](https://github.com/Rupa-Rd/Open-Source-Galaxy/assets/92045934/ad717d9e-b7b5-444f-9652-e92a7d061946)

The fonts and colors combo is not appealing and cards style can be improved too by adding icons and roundness.

**Comment by Rupa-Rd** [comment]
Take a small part of the UI styling and work on it. If you wish to either go for card or icon styling.

**Comment by k0msenapati** [comment]
First of all I want to change font and color then can do the card UI (like include icon for link and set reminder and a better card UI)

**Comment by Rupa-Rd** [comment]
@kom-senapati Go for it!
