### ISSUE TITLE
Creating a project's README file

### ISSUE THREAD

**Issue by Rupa-Rd** [Rupa-Rd/Open-Source-Galaxy#44]
Current README file has contain the outline of why the project has been developed.
The task of the contributor is to edit the existing readme.md file by adding gifs, images and detailed workflow of the website.

**Comment by deepesh611** [comment]
Hi there, @Rupa-Rd, I could work on the `README.md`

**Comment by Rupa-Rd** [comment]
Sure, I've assigned the issue to you. Go ahead!


> Hi there, @Rupa-Rd, I could work on the `README.md`

**Comment by deepesh611** [comment]
@Rupa-Rd, I have submitted a PR with the updated readme file, pls ahve a look

https://github.com/Rupa-Rd/Open-Source-Galaxy/pull/57

**Comment by deepesh611** [comment]
@Rupa-Rd  be sure to close the issue #27 and #44 , and also update the score

gmail: deepeshvcd6273@gmail.com
