### ISSUE TITLE
Creating a Blog Button

### ISSUE THREAD

**Issue by Rupa-Rd** [Rupa-Rd/Open-Source-Galaxy#46]
The blog page has been created by a wonderful contributor, to link the blog page the blog page button is needed.

Tasks should be completed
1. Blog button in the navbar

Important note:
1. Do not change the website's theme and color
2. Go with the button's default theme in the website

**Comment by kratik1237** [comment]
I AM INTERESTED, PLEASE ASSIGN. @Rupa-Rd

**Comment by Rupa-Rd** [comment]
@kratik1237 Go for it!

**Comment by Rupa-Rd** [comment]
This issue has been solved in the PR #52
