### ISSUE TITLE
Improving UI of the website

### ISSUE THREAD

**Issue by deepesh611** [Rupa-Rd/Open-Source-Galaxy#47]
- Adding a good Background to the website
- show 4 tiles isntead of 3. The tiles look too big in the current layout

**Comment by Rupa-Rd** [comment]
@deepesh611 Could you add the screenshots in which layout it shows 4 tiles
![image](https://github.com/Rupa-Rd/Open-Source-Galaxy/assets/102663541/8e3cf51c-2094-478f-a503-d151f25ae4b9)

**Comment by deepesh611** [comment]
Here you go @Rupa-Rd 

![image](https://github.com/Rupa-Rd/Open-Source-Galaxy/assets/123585104/80c8878c-328a-4863-b64d-5b16cbd2067a)

**Comment by Rupa-Rd** [comment]
Could you mention layout size?


> Here you go @Rupa-Rd
> 
> ![image](https://private-user-images.githubusercontent.com/123585104/342369022-80c8878c-328a-4863-b64d-5b16cbd2067a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzk4MjAsIm5iZiI6MTcxOTIzOTUyMCwicGF0aCI6Ii8xMjM1ODUxMDQvMzQyMzY5MDIyLTgwYzg4NzhjLTMyOGEtNDg2My1iNjRkLTViMTZjYmQyMDY3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxNDMyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjFlY2JhMDFkMWFlZmUwMmZlNzUxMjRhZTRjNzI0MTgzYTJlNjhlODRhOTg3NWQ5ZGFkMTUxMGFjNTE0MTlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.auB_WId4u-CLEzicd0Wq29X08AwfRawFjFTuEby-L7I)

**Comment by deepesh611** [comment]
Same grid, just instead of 3 columns, change to 4 columns

**Comment by Rupa-Rd** [comment]
@deepesh611 work on it

**Comment by deepesh611** [comment]
@Rupa-Rd, I have submitted a PR, pls verify the changes and make sure to leave a feedback 👍
