### ISSUE TITLE
Improving Header

### ISSUE THREAD

**Issue by Broken-Kaddu** [Rupa-Rd/Open-Source-Galaxy#6]
General additions, include navigation bar with more options + footer for the front page + the log in page has some issue as shown in picture below, also we could make the cards of the events a bit more interactive along with that add a scrolling banner at the front page to show off the events, that might look cooler.
![nav bar](https://github.com/Rupa-Rd/Open-Source-Galaxy/assets/166910220/f3fcd089-9185-4e44-b931-24b83e91a1fd)
![ui](https://github.com/Rupa-Rd/Open-Source-Galaxy/assets/166910220/96f71816-c183-45f2-96f6-e09a45041580)
![what dev_](https://github.com/Rupa-Rd/Open-Source-Galaxy/assets/166910220/db624c1a-5c09-4ecf-ad76-35c1b35b518b)

**Comment by Rupa-Rd** [comment]
@Broken-Kaddu Work on it!

**Comment by Ayushswirlon** [comment]
can i work on it.

**Comment by Broken-Kaddu** [comment]
> @Broken-Kaddu Work on it!
> 

Sure

**Comment by Rupa-Rd** [comment]
Due to the inactiveness of the contributor, the issue has been transferred to @Mehak-Mattoo
