### ISSUE TITLE
[UI Design] Adding some more Open source programs 

### ISSUE THREAD

**Issue by Meetjain1** [Rupa-Rd/Open-Source-Galaxy#60]
**Describe the solution you'd like**
We can add more opensource programs .

**Describe alternatives you've considered**

**Additional context**

@Rupa-Rd assign this to me i will add more open source programs . I am working under VSOC

**Comment by Rupa-Rd** [comment]
Cool. @Meetjain1 Work on it. Do not change the existing style of the website
