### ISSUE TITLE
[UI Design] Create `About` page

### ISSUE THREAD

**Issue by deepesh611** [Rupa-Rd/Open-Source-Galaxy#65]
**Is your feature request related to a problem? Please describe.**
Create the `About` page 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mu6m** [comment]
hi i made an about page that presents your project

**Comment by mu6m** [comment]
#66 here is the pull request

**Comment by deepesh611** [comment]
> #66 here is the pull request

ooh, i see
thx
